### PR TITLE
Don't prevent duplicate names if lenient-model-deduplication is enabled

### LINKED ISSUE #3786: Naming rules not applied to all schema names
When running https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/resources/Azure.ResourceManager.Resources/src/autorest.md

We get 

```
schema: !<!ObjectSchema> &ref_360
                    type: object
                    apiVersions:
                      - !<!ApiVersion> 
                        version: '2015-12-01'
                    properties:
                      - !<!Property> 
                        schema: *ref_17
                        serializedName: provider
                        language: !<!Languages> 
                          default:
                            name: provider
                            description: 'Service provider: Microsoft.Features'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_18
                        serializedName: resource
                        language: !<!Languages> 
                          default:
                            name: resource
                            description: 'Resource on which the operation is performed: Profile, endpoint, etc.'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_19
                        serializedName: operation
                        language: !<!Languages> 
                          default:
                            name: operation
                            description: 'Operation type: Read, write, delete, etc.'
                        protocol: !<!Protocols> {}
                    serializationFormats:
                      - json
                    usage:
                      - output
                    extensions:
                      x-internal-autorest-anonymous-schema:
                        anonymous: true
                    language: !<!Languages> 
                      default:
                        name: Operation-display <----------------------------------
                        description: The object that represents the operation.
                        namespace: ''

```

And 

```
schema: !<!ObjectSchema> &ref_23
                    type: object
                    apiVersions:
                      - !<!ApiVersion> 
                        version: '2019-10-01'
                      - !<!ApiVersion> 
                        version: '2019-11-01'
                    properties:
                      - !<!Property> 
                        schema: *ref_17
                        serializedName: provider
                        language: !<!Languages> 
                          default:
                            name: provider
                            description: 'Service provider: Microsoft.Resources'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_18
                        serializedName: resource
                        language: !<!Languages> 
                          default:
                            name: resource
                            description: 'Resource on which the operation is performed: Profile, endpoint, etc.'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_19
                        serializedName: operation
                        language: !<!Languages> 
                          default:
                            name: operation
                            description: 'Operation type: Read, write, delete, etc.'
                        protocol: !<!Protocols> {}
                      - !<!Property> 
                        schema: *ref_20
                        serializedName: description
                        language: !<!Languages> 
                          default:
                            name: description
                            description: Description of the operation.
                        protocol: !<!Protocols> {}
                    serializationFormats:
                      - json
                    usage:
                      - output
                    extensions:
                      x-internal-autorest-anonymous-schema:
                        anonymous: true
                    language: !<!Languages> 
                      default:
                        name: OperationDisplay  <----------------------------------
                        description: The object that represents the operation.
                        namespace: ''
```

Not applying naming rules causes the deduplicator to skip this model.

When C# generator runs it applies name cleanup rules resulting in two different models with the same name.

This is a regression after updating to `4.15.442` from `4.15.423`

image

Blocking us from taking generator updates.

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix Azure/autorest#3786

As part of fixing potential duplicates names when **NOT** using `lenient-model-deduplication` with consecutive duplicate words(e.g. FooBarBar -> FooBar) this caused issues when using `lenient-model-deduplication` which counted on the fact that there might be duplicates.

This changes 2 things:
- If `lenient-model-deduplication` is enabled just pick the first styled option(Should be the same behavior as before the previous fix)
- If no compatible names are found throw an error to enable `lenient-model-deduplication`

### CODE REVIEW

File: modelerfour/src/prenamer/naming-utils.ts [hunk 1]
```diff
@@ -64,18 +69,18 @@ export function setNameAllowEmpty(
...
+    // Check if the new name is not yet taken or lenientModelDeduplication is enabled then we don't care about duplicates.
+    if ((newName && !options.existingNames?.has(newName)) || options.lenientModelDeduplication) {
       options.existingNames?.add(newName);
       thing.language.default.name = newName;
       return;
     }
   }
-  // We didn't find a compatible name. Ignoring the renaming silently.
+
+  throw new Error(`Couldn't style name '${initialName}'. It result in duplicate names, tried: [${namingOptions.join(",")}]. You can try using 'modelerfour.lenient-model-deduplication' to allow such duplicates.`);
```
Comment (daviwil) [inline modelerfour/src/prenamer/naming-utils.ts]:
```suggestion
  throw new Error(`Couldn't style name '${initialName}'. All of the following naming possibilities created duplicate names: [${namingOptions.join(",")}]. You can try using 'modelerfour.lenient-model-deduplication' to allow such duplicates.`);
```

**Review by daviwil — APPROVED** [review]
