### PR TITLE
Fix: Circular dependency issue with sibling schemas/definitions. 

### LINKED ISSUE #3630: Error on Circular $ref in policy PR
**Describe the issue**
A clear and concise description of what the problem is. Help me find your problem, don't just drop a vague message and run.

Output
```
WARNING (PreCheck/CheckDuplicateSchemas): Checking for duplicate schemas, this could take a (long) while.  Run with --verbose for more detail.
FATAL: Error: Circular $ref in Model -- #/components/schemas/schemas:0 :: ["#/components/schemas/schemas:0"]
  Error: Plugin prechecker reported failure.
```

The cause is likely this line: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-03-01/policyAssignments.json#L582

A previous api-version with a different ref pattern would pass: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2019-09-01/policyAssignments.json#L586-L594

The definition is a bit wired, but we tried it on swagger, this is not an invalid definition.
image

Please let us know whether this is m4 bug, or there is indeed problem with the swagger spec.

** REQUIRED ** 
**ModelerFour** version:4.15.423
**AutoRest-core** version:3.0.6326
**CommandLine** :`autorest https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/resources/resource-manager/readme.md --tag=package-policy-2020-03 --java ...`
OpenAPI/Swagger file:https://github.com/Azure/azure-rest-api-specs/blob/master/specification/resources/resource-manager/Microsoft.Authorization/stable/2020-03-01/policyAssignments.json

### PR DESCRIPTION
**Pull request by timotheeguerin**
fix Azure/autorest#3630

When a model is following the pattern `$ref and Sibling Elements` described here https://swagger.io/docs/specification/using-ref/

This is causing a circular dependency issue because the model(with the properties) gets removed and the model with the reference get the ref updated to itself.

The solution is to figure out which of the 2 models to delete(The one not being a ref)

Todo:
- [x] Tests
- [x] Changelog

### CODE REVIEW

File: modelerfour/src/quality-precheck/prechecker.ts [hunk 1]
```diff
@@ -336,6 +299,60 @@ export class QualityPreChecker {
...
+    return { remove: schema2, keep: schema1 };
+  }
+
+  private removeDuplicateSchemas(name: string, schema1: DereferencedSchema, schema2: DereferencedSchema) {
+    const { keep: schemaToKeep, remove: schemaToRemove} = this.findSchemaToRemove(schema1, schema2);
+    delete this.input.components!.schemas![schemaToRemove.key];
+    const text = JSON.stringify(this.input);
+    this.input = JSON.parse(
+      text.replace(
+        new RegExp(`"\\#\\/components\\/schemas\\/${schemaToRemove.key}"`, "g"),
```
Comment (daviwil) [inline modelerfour/src/quality-precheck/prechecker.ts:320]: Should we cache this regex or does V8 do that internally?

**Review by daviwil — APPROVED** [review]

File: modelerfour/src/quality-precheck/prechecker.ts (hunk 1 above)
Comment (timotheeguerin) [reply modelerfour/src/quality-precheck/prechecker.ts:320]: well the regex needs the key to change so it shouldn't really be used multiple times

Comment (daviwil) [reply modelerfour/src/quality-precheck/prechecker.ts:320]: Ahhh, yeah, good point
